; Notes:
; priority=1 --> Lower priorities indicate programs that start first and shut down last
; killasgroup=true --> send kill signal to child processes too

; graceful timeout should always be lower than stopwaitsecs to avoid orphan gunicorn workers.
[program:new-bench-frappe-web]
command=/home/thennarasu/new-bench/env/bin/gunicorn -b 127.0.0.1:8000 -w 45 --max-requests 5000 --max-requests-jitter 500 -t 120 --graceful-timeout 30 frappe.app:application --preload
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/thennarasu/new-bench/logs/web.log
stderr_logfile=/home/thennarasu/new-bench/logs/web.error.log
stopwaitsecs=40
killasgroup=true
user=thennarasu
directory=/home/thennarasu/new-bench/sites
startretries=10

[program:new-bench-frappe-schedule]
command=/usr/local/bin/bench schedule
priority=3
autostart=true
stdout_logfile=/home/thennarasu/new-bench/logs/schedule.log
stderr_logfile=/home/thennarasu/new-bench/logs/schedule.error.log
user=thennarasu
directory=/home/thennarasu/new-bench
startretries=10



[program:new-bench-frappe-short-worker]
command=/usr/local/bin/bench worker --queue short,default
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/thennarasu/new-bench/logs/worker.log
stderr_logfile=/home/thennarasu/new-bench/logs/worker.error.log
user=thennarasu
stopwaitsecs=360
directory=/home/thennarasu/new-bench
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10

[program:new-bench-frappe-long-worker]
command=/usr/local/bin/bench worker --queue long,default,short
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/thennarasu/new-bench/logs/worker.log
stderr_logfile=/home/thennarasu/new-bench/logs/worker.error.log
user=thennarasu
stopwaitsecs=1560
directory=/home/thennarasu/new-bench
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10





[program:new-bench-redis-cache]
command=/usr/bin/redis-server /home/thennarasu/new-bench/config/redis_cache.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/thennarasu/new-bench/logs/redis-cache.log
stderr_logfile=/home/thennarasu/new-bench/logs/redis-cache.error.log
user=thennarasu
directory=/home/thennarasu/new-bench/sites
startretries=10

[program:new-bench-redis-queue]
command=/usr/bin/redis-server /home/thennarasu/new-bench/config/redis_queue.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/thennarasu/new-bench/logs/redis-queue.log
stderr_logfile=/home/thennarasu/new-bench/logs/redis-queue.error.log
user=thennarasu
directory=/home/thennarasu/new-bench/sites
startretries=10




[group:new-bench-web]
programs=new-bench-frappe-web




[group:new-bench-workers]
programs=new-bench-frappe-schedule,new-bench-frappe-short-worker,new-bench-frappe-long-worker




[group:new-bench-redis]
programs=new-bench-redis-cache,new-bench-redis-queue
